server {
    listen 80;
    listen [::]:80;
    server_name notify.example.com;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/personal-notify-acme;
    }
    location / { return 308 https://notify.example.com$request_uri; }
}
